projetoBragantec/projetoBragantec/urls.py
from django.contrib import admin
from django.urls import path, include
from cruds_adminlte.urls import crud_for_model, crud_for_app
from django.apps import apps
from sistema.forms import AlteracoesForm
from cruds_adminlte.crud import CRUDMixin
from sistema.models import Avaliador, Diretor

class MixinList(CRUDMixin):
    def get_context_data(self, *args, **kwargs):
        context = super(Mixin, self).get_context_data(*args, **kwargs)
        context['avaliadores'] = Avaliador.objects.all()
        context['diretores'] = Diretor.objects.all()
        return context


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sistema.urls')),
]

urlpatterns += crud_for_model(
	apps.get_model('sistema', 'Projeto'),
	views=['delete', 'detail', 'update', 'list'], 
	login_required=True, update_form=AlteracoesForm, mixin=MixinList)

urlpatterns += crud_for_model(
    apps.get_model('sistema', 'Avaliador'),
    views=['list'], login_required=True)

urlpatterns += crud_for_model(
    apps.get_model('sistema', 'Diretor'),
    views=['list'], login_required=True)

projetoBragantec/sistema/urls.py
from django.urls import path, include
import sistema.views
from django.contrib.auth import views

urlpatterns = [
	path('', sistema.views.index, name='index'),
	path('login/', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('dashboard/', sistema.views.dashboard, name='dashboard'),
	path('registro-autor/', sistema.views.register_autor, name='register_autor'),
	path('submeter-projeto/', sistema.views.submit_project, name='submit_project'),
	path('confirmar/', sistema.views.confirm, name='confirm'),
	path('registro-usuario/', sistema.views.register_user, name='register_user'),
	path('registro-orientador/', sistema.views.register_orientador, name='register_orientador'),
	path('aceitar-submissao/<int:pk>', sistema.views.accept_submission, name='accept_submission'),
	path('rejeitar-submissao/<int:pk>', sistema.views.reject_submission, name='reject_submission'),
	path('gerar-pdf/', sistema.views.generate_pdf, name='generate_pdf'),
	path('baixar-arquivo/<int:pk>', sistema.views.download_archive, name='download_archive'),
	path('registro-avaliador/', sistema.views.register_avaliador, name='register_avaliador'),
	path('gerar-docx/', sistema.views.generate_docx, name='generate_docx'),
	path('gerar-xlsx/', sistema.views.generate_xlsx, name='generate_xlsx'),
	path('criar-evento/', sistema.views.create_event, name='create_event'),
]

projetoBragantec/sistema/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser,
    UserManager)
from django.conf import settings

class User(AbstractUser):

    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)
    is_avaliador = models.BooleanField('É avaliador?', blank=True, default=False)
    is_diretor = models.BooleanField('É Diretor?', blank=True, default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class Autor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    email = models.EmailField('E-mail', unique=True)
    nome = models.CharField('Nome', max_length=100)
    dt_nasc = models.DateField('Data de Nascimento', default=None, help_text='Por favor use o seguinte formato: YYYY-MM-DD')
    curso = models.CharField('Curso', max_length=100,blank=True)
    serie = models.CharField('Série', max_length=100,blank=True)
    instituicao = models.CharField('Instituição', max_length=100)
    objects = UserManager()
    def __str__(self):
        return self.email

    def get_nome(self):
        return self.nome

    def get_email(self, user_id):
        if user_id == self.user:
            return self.email

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

class Orientador(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    email = models.EmailField('E-mail', unique=True)
    nome = models.CharField('Nome', max_length=100)
    instituicao = models.CharField('Instituição', max_length=100)
    objects = UserManager()
    def __str__(self):
        return self.email

    def get_email(self, user_id):
        if user_id == self.user:
            return self.email

    class Meta:
        verbose_name = 'Orientador'
        verbose_name_plural = 'Orientadores'


class Projeto(models.Model):
    titulo = models.CharField(max_length=100, default=None)
    resumo = models.CharField(max_length=200)
    areas = [('CHL', 'Ciências Humanas e Linguagens'), ('CNE', 'Ciências da Natureza e Exatas'), ('I', 'Informática'), ('E', 'Engenharias')]
    area = models.CharField(choices=areas, max_length=100)
    palavras_chave = models.CharField(max_length=30)
    introducao = models.CharField(max_length=500, default=None)
    objetivos = models.CharField(max_length=500, default=None)
    material = models.CharField(max_length=500, default=None)
    metodologia = models.CharField(max_length=500, default=None)
    resultados = models.CharField(max_length=500, default=None)
    referencias_bibliograficas  = models.CharField(max_length=500, default=None)
    plano_pesquisa = models.FileField(upload_to='uploads/', blank=True)
    link_video = models.URLField(max_length=100)
    email_autor_1 = models.EmailField(max_length=100, default=None, blank=True, null=True)
    email_autor_2 = models.EmailField(max_length=100, default=None, blank=True, null=True)
    email_autor_3 = models.EmailField(max_length=100, default=None, blank=True, null=True)
    email_orientador_1 = models.EmailField(max_length=100, default=None, blank=True, null=True)
    email_orientador_2 = models.EmailField(max_length=100, default=None, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    alteracoes = models.CharField(max_length=500, default=None, blank=True, null=True)
    opcoes = [('AA', 'Aguardando Avaliação'), ('R', 'Rejeitado'), ('A', 'Aceito')]
    status = models.CharField(max_length=100, default=opcoes[0][1], choices=opcoes)

    class Meta:
        verbose_name = "Projeto"
        verbose_name_plural = "Projetos"

class Avaliador(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    nome = models.CharField('Nome', max_length=100)
    link_curriculo = models.URLField(max_length=100)
    titulacao = models.CharField(max_length=100)
    areas = [('CHL', 'Ciências Humanas e Linguagens'), ('CNE', 'Ciências da Natureza e Exatas'), ('I', 'Informática'), ('E', 'Engenharias')]
    area = models.CharField(choices=areas, max_length=100)

    class Meta:
        verbose_name = 'Avaliador'
        verbose_name_plural = 'Avaliadores'

class Diretor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    nome = models.CharField('Nome', max_length=100)
    areas = [('CHL', 'Ciências Humanas e Linguagens'), ('CNE', 'Ciências da Natureza e Exatas'), ('I', 'Informática'), ('E', 'Engenharias')]
    area = models.CharField(choices=areas, max_length=100)

    class Meta:
        verbose_name = 'Diretor'
        verbose_name_plural = 'Diretores'

class Evento(models.Model):
    titulo = models.CharField('Título', max_length=100)

    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventos'
            
        

projetoBragantec/sistema/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Projeto, Autor, User, Orientador, Avaliador
from django.contrib.auth import authenticate, login, get_user_model
from .forms import SubmitForm, AutorForm, RegisterForm, OrientadorForm, AvaliadorForm, EventoForm
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from cruds_adminlte.crud import CRUDView
import io
from django.http import FileResponse, HttpResponse
from reportlab.pdfgen import canvas
from docx import *
from openpyxl import Workbook

User = get_user_model()

def index(request):
	return render(request, 'index.html', {})

@login_required
def dashboard(request):
	avaliadores = Avaliador.objects.filter(user_id=request.user)

	avaliadores = list(avaliadores)

	existe = False
	if len(avaliadores) is not 0:
		existe = True
	
	return render(request, 'dashboard.html', {'existe': existe})

@login_required
def register_avaliador(request):
	if request.user.is_avaliador:

		if request.method == 'POST':
			form = AvaliadorForm(request.POST)
			if form.is_valid():
				avaliador = form.save(commit=False)
				avaliador.user_id = request.user.id
				avaliador.save()
				return redirect('dashboard')
		else:
			form = AvaliadorForm()

		return render(request, 'registration/register_avaliador.html', {'form': form})
	else:
		return redirect('dashboard')

def register_user(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(username=user.username, 
				password=form.cleaned_data['password1']
				)
			login(request, user)
			return redirect('dashboard')
	else:
		form = RegisterForm()
	return render(request, 'register_user.html', {'form': form})

@login_required
@csrf_exempt
def register_autor(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		return redirect('dashboard')
	else: 
		projeto = Projeto.objects.filter(user_id=request.user)
		projeto = list(projeto)

		response_data = {}

		existe_projeto = False

		if len(projeto) is not 0:
			existe_projeto = True

		if request.method == 'POST':
			data = request.POST

			email = data['email']
			nome = data['nome']
			dt_nasc = data['dt_nasc']
			curso = data['curso']
			serie = data['serie']
			instituicao = data['instituicao']

			response_data['email'] = email
			response_data['nome'] = nome
			response_data['dt_nasc'] = dt_nasc
			response_data['curso'] = curso
			response_data['serie'] = serie
			response_data['instituicao'] = instituicao

			Autor.objects.create(email=email, 
				nome=nome, 
				dt_nasc=dt_nasc, curso=curso, 
				serie=serie, instituicao=instituicao, user_id=request.user.id)

			return JsonResponse(response_data)
		else:

			form = AutorForm()
		ultimo_id = Autor.objects.latest('pk').pk

		return render(request, 'registration/register.html', {'form': form, 'existe_projeto': existe_projeto, 'ultimo_id': ultimo_id})
	

@login_required
def submit_project(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		return redirect('dashboard')
	else:
		user_id = request.user.id

		projeto = Projeto.objects.filter(user_id=request.user)
		projeto = list(projeto)
		existe_projeto = False
		if len(projeto) is not 0:
			existe_projeto = True

		orientadores = Orientador.objects.filter(user_id=user_id).values_list('email')
		autores = Autor.objects.filter(user_id = user_id).values_list('email')
		orientadores = list(orientadores)
		autores = list(autores)

		if request.method == 'POST':
			form = SubmitForm(request.POST)
			if form.is_valid():
				projeto = form.save(commit=False)
				
				if len(autores) == 1:
					projeto.email_autor_1 = autores[0][0]
					projeto.email_autor_2 = ''
					projeto.email_autor_3 = ''
				elif len(autores) == 2:
					projeto.email_autor_1 = autores[0][0]
					projeto.email_autor_2 = autores[1][0]
					projeto.email_autor_3 = ''
				elif len(autores) == 3:
					projeto.email_autor_1 = autores[0][0]
					projeto.email_autor_2 = autores[1][0]
					projeto.email_autor_3 = autores[2][0]

				if len(orientadores) == 1:
					projeto.email_orientador_1 = orientadores[0][0]
					projeto.email_orientador_2 = ''
				elif len(orientadores) == 2:
					projeto.email_orientador_1 = orientadores[0][0]
					projeto.email_orientador_2 = orientadores[1][0]

				projeto.user_id = user_id

				projeto.save()
				return redirect('confirm')
		else:
			form = SubmitForm()
		return render(request, 'registration/submit.html', {'form': form, 'existe_projeto': existe_projeto})

@login_required
def confirm(request):
	user_id = request.user.id
	orientadores = Orientador.objects.filter(user_id=user_id)
	autores = Autor.objects.filter(user_id = user_id)
	projeto = Projeto.objects.filter(user_id=user_id)
	return render(request, 'registration/confirm.html', 
		{'autores': autores,
		'projeto': projeto,
		'orientadores': orientadores})

@login_required
def register_orientador(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		return redirect('dashboard')
	else:
		projeto = Projeto.objects.filter(user_id=request.user)
		projeto = list(projeto)

		response_data = {}

		existe_projeto = False

		if len(projeto) is not 0:
			existe_projeto = True
		response_data = {}

		if request.method == 'POST':
			data = request.POST

			email = data['email']
			nome = data['nome']
			instituicao = data['instituicao']

			response_data['email'] = email
			response_data['nome'] = nome
			response_data['instituicao'] = instituicao

			Orientador.objects.create(
				email=email, 
				nome=nome, 
				instituicao=instituicao, 
				user_id=request.user.id)

			return JsonResponse(response_data)
		form = OrientadorForm()
		return render(request, 'registration/register_orientador.html', {'form': form, 'existe_projeto': existe_projeto})

@login_required
def accept_submission(request, pk):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		projeto = get_object_or_404(Projeto.objects.all(), pk=pk)
		if request.method == 'POST':
			data = request.POST
			projeto.status = data['status']
			projeto.pk = pk
			projeto.save()
			return redirect('sistema_projeto_list')
		return render(request, 'admin_actions/accept_submission.html', {'projeto':projeto})
	else:
		return redirect('dashboard')

@login_required
def reject_submission(request, pk):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		projeto = get_object_or_404(Projeto.objects.all(), pk=pk)
		if request.method == 'POST':
			data = request.POST
			projeto.status = data['status']
			projeto.pk = pk
			projeto.save()
			return redirect('sistema_projeto_list')
		return render(request, 'admin_actions/reject_submission.html', {'projeto':projeto})
	else:
		return redirect('dashboard')

@login_required
def generate_pdf(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		if request.method == 'POST':
			data = request.POST
			buffer1 = io.BytesIO()
			p = canvas.Canvas(buffer1)
			x = 720
			for campo in data:
				if campo != 'csrfmiddlewaretoken':
					p.drawString(100, x, '{}: {}'.format(campo, data[campo]))
					x-=20
				else:
					pass

			p.showPage()

			p.save()

			buffer1.seek(0)

			return FileResponse(buffer1, as_attachment=True, filename='projeto.pdf')
	else:
		return redirect('dashboard')

@login_required
def generate_docx(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		if request.method == 'POST':
			data = request.POST
			document = Document()

			for campo in data:
				if campo != 'csrfmiddlewaretoken':
					document.add_paragraph('{}: {}'.format(campo, data[campo]))
				else:
					pass

			document.add_page_break()

			response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')

			response['Content-Disposition'] = 'attachment; filename=projeto.docx'

			document.save(response)

			return response
	else:
		return redirect('dashboard')

@login_required
def generate_xlsx(request):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		if request.method == 'POST':
			data = request.POST

			wb = Workbook()
			ws = wb.active

			for campo in data:
				if campo != 'csrfmiddlewaretoken':
					ws.append([campo, data[campo]])

			response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
			response['Content-Disposition'] = 'attachment; filename=projeto.xlsx'
			wb.save(response)
			return response
	else:
		return redirect('dashboard')

@login_required
def download_archive(request, pk):
	if request.user.is_staff or request.user.is_avaliador or request.user.is_diretor:
		projeto = get_object_or_404(Projeto.objects.all(), pk=pk)

		return render(request, 'admin_actions/download_archive.html', {'projeto': projeto})
	else:
		return redirect('dashboard')

@login_required
def create_event(request):
	if request.user.is_staff:
		form = EventoForm()
		return render(request, 'admin_actions/create_event.html', {'form': form})
	else:
		return redirect('dashboard')

projetoBragantec/sistema/templates/admin_actions/accept_submission.html
{% extends "dashboard.html" %}

{% block body %}

	{% block nav_header %}
        {% include 'adminlte/lib/_main_header.html' %}
    {% endblock %}

    {% block nav_sidebar %}
        {% include 'adminlte/lib/_main_sidebar.html' %}
    {% endblock %}

    {% block content-wrapper %}
    <div class="content-wrapper">
  	<h1>Aceitar o projeto '{{ projeto.titulo }}'?</h1>

	<form action="{% url 'accept_submission' projeto.id %}" method="POST">
	    {% csrf_token %}
	    <p>
	    	<input type="hidden" name="status" id="id_status" value="A">
	    </p>
		<p>
	    	<button type="submit" class="btn btn-success">Aceitar</button>
	    </p>
	</form>

	

    {% block nav_footer %}
        {% include 'adminlte/lib/_main_footer.html' %}
    {% endblock %}
    
    {% endblock content-wrapper %}
	</div>

{% endblock %}

projetoBragantec/sistema/templates/admin_actions/create_event.html
{% extends "dashboard.html" %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block title_outer %}
	<title>
		{% block title %} 
			Criar Evento
		{% endblock %}
	</title>
{% endblock %}

<div>
	{% block nav_header %}
        {% include 'adminlte/lib/_main_header.html' %}
    {% endblock %}

    {% block nav_sidebar %}
        {% include 'adminlte/lib/_main_sidebar.html' %}
    {% endblock %}

    {% block content-wrapper %}
    <div class="content-wrapper">
    	{% block content-header %}
    	<section class="content-header">
    		<div class="breadcrumbs">
    			<ul>
    				{% block breadcrumbs %}
			    		{{ block.super }}
			    		<li>/</li>
			    		<li><a href="{% url 'create_event' %}">Criar Evento</a></li>
			    	{% endblock breadcrumbs %}
    			</ul>
    		</div>
    		
    	</section>
    	{% endblock content-header%}

    	{% block content-outer %}
    	<section>
    		<div class="content">
				<form method='post'>
					{% csrf_token %}
					<fieldset>
					{% for field in form %}
						<div>
							{{ field.label_tag }}
					        {{ field }}
					        {{ field.errors }}
					    </div>
					{% endfor %}
					<br>
					<div>
						<button type="submit">Cadastrar</button>
					</div>
					</fieldset>
				</form>
			</div>
    	</section>
    	{% endblock content-outer %}
    </div>
   	{% endblock content-wrapper %}
</div>

projetoBragantec/sistema/templates/admin_actions/download_archive.html
{% extends "dashboard.html" %}

{% block js %}
<script type="text/javascript">

    function selecionarTudo(){
        $(".campo").attr('checked', 'true');
    };

	$(document).ready(function(){

        $('#tipoArquivo').change(function(){
            var opcao = $(this).val();
            switch(opcao){
                case 'pdf':
                    $("#campos").attr("action", "{% url 'generate_pdf' %}");
                    break;
                case 'docx':
                    $('#campos').attr("action", "{% url 'generate_docx' %}");
                    break;
                case 'xlsx':
                    $('#campos').attr("action", "{% url 'generate_xlsx' %}");
                    break;
            }
        });

	});
</script>
{% endblock js%}

{% block body %}

	{% block nav_header %}
        {% include 'adminlte/lib/_main_header.html' %}
    {% endblock %}

    {% block nav_sidebar %}
        {% include 'adminlte/lib/_main_sidebar.html' %}
    {% endblock %}

    {% block content-wrapper %}
    <div class="content-wrapper">
        <label>Tipo de arquivo:</label>
        <select id='tipoArquivo'>
            <option value='docx'>DOCX</option>
            <option value='pdf'>PDF</option>
            <option value='xlsx'>XLSX</option>
        </select>
    	<h2 style="margin-top: 0px; text-align: center;">Selecione os campos para gerar o arquivo: </h2>
    	<form method="post" id="campos">
    	{% csrf_token %}
    	<table class="table table-responsive table-bordered table-hover">
    		<thead>
    			<th><input type="checkbox" name="all" id="tudo" onClick="selecionarTudo();"></th>
    			<th>Campo</th>
    			<th>Valor</th>
    		</thead>
    		<tbody>
    			<tr>
    				<td><input type="checkbox" name="titulo" value="{{ projeto.titulo }}" class="campo"></td>
    				<td>Título</td>
    				<td>{{ projeto.titulo }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="resumo" value="{{ projeto.resumo }}" class="campo"></td>
    				<td>Resumo</td>
    				<td>{{ projeto.resumo }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="area" value="{{ projeto.area }}" class="campo"></td>
    				<td>Área</td>
    				<td>{{ projeto.area }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="palavras_chave" value="{{ projeto.palavras_chave}}" class="campo"></td>
    				<td>Palavras Chave</td>
    				<td>{{ projeto.palavras_chave }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="introducao" value="{{ projeto.introducao }}" class="campo"></td>
    				<td>Introdução</td>
    				<td>{{ projeto.introducao }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="objetivos" value="{{ projeto.objetivos }}" class="campo"></td>
    				<td>Objetivos</td>
    				<td>{{ projeto.ojetivos }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="material" value="{{ projeto.material }}" class="campo"></td>
    				<td>Material</td>
    				<td>{{ projeto.material }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="metodologia" value="{{ projeto.metodologia }}" class="campo"></td>
    				<td>Metodologia</td>
    				<td>{{ projeto.metodologia }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="resultados" value="{{ projeto.resultados }}" class="campo"></td>
    				<td>Resultados</td>
    				<td>{{ projeto.resultados }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="referencias_bibliograficas" value="{{ projeto.referencias_bibliograficas }}" class="campo"></td>
    				<td>Referências Bibliogréficas</td>
    				<td>{{ projeto.referencias_bibliograficas }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="link_video" value="{{ projeto.link_video }}" class="campo"></td>
    				<td>Link do Vídeo</td>
    				<td>{{ projeto.link_video }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="email_autor_1" value="{{ projeto.email_autor_1 }}" class="campo"></td>
    				<td>Email Autor 1</td>
    				<td>{{ projeto.email_autor_1 }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="email_autor_2" value="{{ projeto.email_autor_2 }}" class="campo"></td>
    				<td>Email Autor 2</td>
    				<td>{{ projeto.email_autor_2 }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="email_autor_3" value="{{ projeto.email_autor_3 }}" class="campo"></td>
    				<td>Email Autor 3</td>
    				<td>{{ projeto.email_autor_3 }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="email_orientador_1" value="{{ projeto.email_orientador_1 }}" class="campo"></td>
    				<td>Email Orientador 1</td>
    				<td>{{ projeto.email_orientador_1 }}</td>
    			</tr>
    			<tr>
    				<td><input type="checkbox" name="email_orientador_2" value="{{ projeto.email_orientador_2}}" class="campo"></td>
    				<td>Email Orientador 2</td>
    				<td>{{ projeto.email_orientador_2 }}</td>
    			</tr>
    		</tbody>
    	</table>
    		<input type="submit" value="Baixar">
    	</form>
    	
  		
	{% endblock %}
	
    </div>

{% endblock %}

projetoBragantec/sistema/templates/admin_actions/reject_submission.html
{% extends "dashboard.html" %}

{% block body %}

	{% block nav_header %}
        {% include 'adminlte/lib/_main_header.html' %}
    {% endblock %}

    {% block nav_sidebar %}
        {% include 'adminlte/lib/_main_sidebar.html' %}
    {% endblock %}

    {% block content %}
  	<h1>Rejeitar o projeto '{{ projeto.titulo }}'?</h1>

	<form action="{% url 'reject_submission' projeto.id %}" method="POST">
	    {% csrf_token %}
	    <p>
	    	<input type="hidden" name="status" id="id_status" value="R">
	    </p>
		<p>
	    	<button type="submit" class="btn btn-danger">Rejeitar</button>
	    </p>
	</form>

	{% endblock %}

    {% block nav_footer %}
        {% include 'adminlte/lib/_main_footer.html' %}
    {% endblock %}

{% endblock %}